name:                nand2tetrs-parsec-assembler
version:             0.1.0.0
github:              prolific-dabbler/nand2tetrs-parsec-assembler
license:             BSD3
author:              "Alec Featherston"
maintainer:          "alecfeatherston@gmail.com"
copyright:           "2019 Alec Featherston"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/prolific-dabbler/nand2tetrs-parsec-assembler.git#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- bytestring
- containers

library:
  source-dirs: src

executables:
  nand-assembler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nand2tetrs-parsec-assembler

tests:
  parsec-tutorial-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nand2tetrs-parsec-assembler
